allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
onlyBuiltDependencies:
  - esbuild
  - electron
  - electron-winstaller
  - onnxruntime-node
  - protobufjs
  - sharp
overrides:
  sharp: 0.35.3
